# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2'

gem 'dotenv', '~> 3.1'
gem 'pg', '~> 1.5'
gem 'sequel', '~> 5.86'

group :development do
  gem 'rake', '~> 13.2'
end

gem "max_bot_api", "~> 0.3"
